SET NAMES utf8mb4;

CREATE DATABASE IF NOT EXISTS bids CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS iam CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS alb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

GRANT ALL PRIVILEGES ON iam.* TO 'bids'@'%';
GRANT ALL PRIVILEGES ON alb.* TO 'bids'@'%';
FLUSH PRIVILEGES;
