logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [%15.15t] %-40.40logger{39} : %m%n"
  level:
    root: INFO
    com.apig: INFO
    org.springframework.cloud.gateway: INFO
    reactor.netty: WARN
