server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    gzip on;
    gzip_types text/plain application/javascript application/json text/css;

    location /apig/ {
        proxy_pass http://apig-gateway:8080/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Authorization $http_authorization;
    }

    location ^~ /bids/assets/ {
        alias /usr/share/nginx/html/assets/;
    }

    location /bids/ {
        alias /usr/share/nginx/html/;
        try_files $uri $uri/ /index.html;
    }

    location = /bids {
        return 301 /bids/;
    }

    location /api/config/ {
        proxy_pass http://bids-config:8081/api/config/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Authorization $http_authorization;
    }

    location /api/runtime/ {
        proxy_pass http://bids-exec:8082/api/runtime/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Authorization $http_authorization;
    }
}
