package com.yeswater.alb.controlplane.service;

import com.yeswater.alb.controlplane.snapshot.RoutingSnapshot;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

@Component
public class CaddyConfigRenderer {

    /**
     * 根据路由快照生成 Caddyfile 文本。
     */
    public String render(RoutingSnapshot snapshot) {
        StringBuilder builder = new StringBuilder();
        builder.append("# Generated by alb-controlplane v").append(snapshot.version()).append('\n');
        builder.append("{\n\tadmin off\n}\n\n");

        Map<String, List<RoutingSnapshot.SnapshotRoute>> byHost = snapshot.routes().stream()
                .collect(Collectors.groupingBy(RoutingSnapshot.SnapshotRoute::host));

        for (Map.Entry<String, List<RoutingSnapshot.SnapshotRoute>> entry : byHost.entrySet()) {
            String host = entry.getKey();
            RoutingSnapshot.SnapshotRoute route = entry.getValue().get(0);
            builder.append("http://").append(host).append(" {\n");
            if (route.redirectUrl() != null && !route.redirectUrl().isBlank()) {
                builder.append("\tredir ").append(route.redirectUrl()).append("{uri} permanent\n");
            } else {
                builder.append("\treverse_proxy ").append(stripScheme(route.targetUrl())).append('\n');
                appendHeaderDirectives(builder, route.headers());
            }
            builder.append("}\n\n");
        }
        return builder.toString();
    }

    private void appendHeaderDirectives(StringBuilder builder, List<RoutingSnapshot.SnapshotHeaderPolicy> headers) {
        for (RoutingSnapshot.SnapshotHeaderPolicy policy : headers) {
            if (!"request".equalsIgnoreCase(policy.direction())) {
                continue;
            }
            if ("set".equalsIgnoreCase(policy.op())) {
                builder.append("\theader_up ").append(policy.headerKey())
                        .append(' ').append(policy.headerValue()).append('\n');
            } else if ("add".equalsIgnoreCase(policy.op())) {
                builder.append("\theader_up +").append(policy.headerKey())
                        .append(' ').append(policy.headerValue()).append('\n');
            } else if ("remove".equalsIgnoreCase(policy.op())) {
                builder.append("\theader_up -").append(policy.headerKey()).append('\n');
            }
        }
    }

    private String stripScheme(String targetUrl) {
        if (targetUrl.startsWith("http://")) {
            return targetUrl.substring("http://".length());
        }
        if (targetUrl.startsWith("https://")) {
            return targetUrl.substring("https://".length());
        }
        return targetUrl;
    }
}
