package com.yeswater.alb.controlplane.service;

import com.yeswater.alb.controlplane.snapshot.RoutingSnapshot;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

/**
 * 根据路由快照生成 nginx 配置（与 deploy/nginx/nginx.dev.conf 语义一致）。
 */
@Component
public class NginxConfigRenderer {

    /**
     * 生成 nginx server 块文本。
     */
    public String render(RoutingSnapshot snapshot) {
        StringBuilder builder = new StringBuilder();
        builder.append("# Generated by alb-controlplane v").append(snapshot.version()).append('\n');
        builder.append("map $http_upgrade $connection_upgrade {\n");
        builder.append("    default upgrade;\n");
        builder.append("    ''      close;\n");
        builder.append("}\n\n");
        builder.append("server {\n");
        builder.append("    listen 80;\n");
        builder.append("    listen ").append(snapshot.dataplaneListenPort()).append(";\n");
        builder.append("    server_name yeds.com www.yeds.com localhost 127.0.0.1;\n\n");

        List<RoutingSnapshot.SnapshotRoute> routes = new ArrayList<>(snapshot.routes());
        routes.sort(Comparator.comparingInt((RoutingSnapshot.SnapshotRoute r) -> -pathSpecificity(r.pathPattern())));

        for (RoutingSnapshot.SnapshotRoute route : routes) {
            appendLocation(builder, route);
        }

        builder.append("\n    location = / {\n        return 302 /bids/;\n    }\n");
        builder.append("    location / {\n        return 404;\n    }\n");
        builder.append("}\n");
        return builder.toString();
    }

    private void appendLocation(StringBuilder builder, RoutingSnapshot.SnapshotRoute route) {
        String pathPrefix = normalizePrefix(route.pathPattern());
        builder.append("    location ").append(pathPrefix).append(" {\n");
        if (route.redirectUrl() != null && !route.redirectUrl().isBlank()) {
            builder.append("        return 302 ").append(route.redirectUrl()).append(";\n");
        } else {
            String proxyPass = ensureTrailingSlash(route.targetUrl());
            builder.append("        proxy_pass ").append(proxyPass).append(";\n");
            builder.append("        proxy_http_version 1.1;\n");
            builder.append("        proxy_set_header Host $host;\n");
            builder.append("        proxy_set_header X-Real-IP $remote_addr;\n");
            builder.append("        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n");
            builder.append("        proxy_set_header X-Forwarded-Proto $scheme;\n");
            if (route.websocketEnabled()) {
                builder.append("        proxy_set_header Upgrade $http_upgrade;\n");
                builder.append("        proxy_set_header Connection $connection_upgrade;\n");
            }
            appendHeaderDirectives(builder, route.headers());
        }
        builder.append("    }\n\n");
    }

    private String ensureTrailingSlash(String targetUrl) {
        return targetUrl.endsWith("/") ? targetUrl : targetUrl + "/";
    }

    private void appendHeaderDirectives(StringBuilder builder, List<RoutingSnapshot.SnapshotHeaderPolicy> headers) {
        if (headers == null) {
            return;
        }
        for (RoutingSnapshot.SnapshotHeaderPolicy policy : headers) {
            if (!"request".equalsIgnoreCase(policy.direction())) {
                continue;
            }
            if ("set".equalsIgnoreCase(policy.op())) {
                builder.append("        proxy_set_header ").append(policy.headerKey())
                        .append(' ').append(policy.headerValue()).append(";\n");
            } else if ("remove".equalsIgnoreCase(policy.op())) {
                builder.append("        proxy_set_header ").append(policy.headerKey()).append(" \"\";\n");
            }
        }
    }

    private String normalizePrefix(String pathPattern) {
        if (pathPattern == null || pathPattern.isBlank() || "/**".equals(pathPattern)) {
            return "/";
        }
        if (pathPattern.endsWith("/**")) {
            return pathPattern.substring(0, pathPattern.length() - 2);
        }
        return pathPattern.endsWith("/") ? pathPattern : pathPattern + "/";
    }

    private int pathSpecificity(String pathPattern) {
        return pathPattern == null ? 0 : pathPattern.length();
    }

}
